apiVersion: apps/v1
kind: Deployment
metadata:
  name: myservice2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myservice2
  template:
    metadata:
      labels:
        app: myservice2
    spec:
      containers:
      - name: myservice2
        image: nginx:latest
        ports:
        - containerPort: 80

